name: filmes_em_cartaz
description: Projeto de Catálogo de Filmes

publish_to: 'none'

version: 1.1.1+5

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  cached_network_image: ^3.2.0
  youtube_player_flutter: ^8.0.0
  mobx: ^2.1.1
  flutter_modular: ^5.0.3
  flutter_mobx: ^2.0.6+4
  google_fonts: ^3.0.1
  youtube_player_iframe: ^3.1.0
  shimmer: ^2.0.0
  flutter_native_splash: ^2.2.16

dev_dependencies:
  build_runner:
  mobx_codegen:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  modular_test: ^2.0.0

flutter:

  uses-material-design: true

